import { CartesianGrid, Cell, ResponsiveContainer, Scatter, ScatterChart as RechartsScatter, Tooltip, XAxis, YAxis, ZAxis } from 'recharts';
import type { Earthquake } from '@/types';

const colors = ['#f43f5e', '#fb7185', '#fb923c', '#fbbf24', '#fcd34d', '#fde68a'];
/** Renders or coordinates empty for this frontend module. */
function Empty() { return <div className="flex h-[220px] items-center justify-center rounded-2xl border border-white/10 bg-black/10 text-sm text-white/45">No matching earthquake data</div>; }
// Rank events by magnitude with a shallow-depth tie-breaker so the scatter chart emphasizes notable records.
function rank(events: Earthquake[]) { return events.map((event) => ({ ...event, magnitude: Number(event.magnitude ?? 0), depth: Number(event.depth ?? 0), score: Number(event.magnitude ?? 0) * 10 + Math.max(0, 120 - Number(event.depth ?? 0)) / 12 })).sort((a, b) => b.score - a.score).slice(0, 6).map((event, index) => ({ ...event, rank: index + 1 })); }

/** Renders or coordinates magnitude depth chart for this frontend module. */
export function MagnitudeDepthChart({ events }: { events: Earthquake[] }) {
  // Plot the highest-ranked events with depth on the vertical axis and magnitude-driven bubble size.
  const ranked = rank(events); if (!ranked.length) return <Empty />; const min = Math.min(...ranked.map((event) => event.magnitude)); const max = Math.max(...ranked.map((event) => event.magnitude)); const depth = Math.max(...ranked.map((event) => event.depth), 1);
  return <div className="space-y-4"><div className="rounded-2xl border border-white/10 bg-slate-950/40 p-2"><ResponsiveContainer width="100%" height={240}><RechartsScatter margin={{ top: 12, right: 12, bottom: 8, left: 4 }}><CartesianGrid stroke="rgba(255,255,255,.08)" strokeDasharray="4 4" /><XAxis type="number" dataKey="magnitude" domain={[Math.max(0, min - .3), max + .3]} tick={{ fill: '#94a3b8', fontSize: 11 }} /><YAxis type="number" dataKey="depth" reversed domain={[0, depth + 20]} tick={{ fill: '#94a3b8', fontSize: 11 }} /><ZAxis type="number" dataKey="score" range={[140, 520]} /><Tooltip /><Scatter data={ranked} fill="#f97316">{ranked.map((event) => <Cell key={event.id} fill={colors[(event.rank - 1) % colors.length]} />)}</Scatter></RechartsScatter></ResponsiveContainer><p className="px-2 text-[11px] text-white/45">Bubble size reflects magnitude and shallowness.</p></div><div className="grid gap-2 sm:grid-cols-2">{ranked.map((event) => <div key={event.id} className="flex gap-3 rounded-xl border border-white/10 bg-black/20 px-3 py-2.5"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full text-[11px] font-black text-white" style={{ backgroundColor: colors[(event.rank - 1) % colors.length] }}>{event.rank}</span><div className="min-w-0"><p className="text-sm font-semibold text-white">{event.place}</p><p className="text-xs text-white/55">M{event.magnitude.toFixed(1)} · {Math.round(event.depth)} km</p></div></div>)}</div></div>;
}

/** Renders or coordinates depth chart for this frontend module. */
export function DepthChart({ events }: { events: Earthquake[] }) {
  // Group valid events into shallow, mid-depth, and deep bands for a compact distribution chart.
  if (!events.length) return <Empty />; const segments = [{ label: 'Near Surface', value: events.filter((e) => e.depth < 70).length, color: '#22d3ee' }, { label: 'Mid-Depth', value: events.filter((e) => e.depth >= 70 && e.depth < 300).length, color: '#a78bfa' }, { label: 'Very Deep', value: events.filter((e) => e.depth >= 300).length, color: '#fb7185' }]; const total = segments.reduce((sum, item) => sum + item.value, 0); if (!total) return <Empty />; const radius = 54; const circumference = 2 * Math.PI * radius; let offset = 0;
  return <div className="grid grid-cols-1 gap-4 md:grid-cols-[190px_minmax(0,1fr)] md:items-center"><svg viewBox="0 0 160 160" className="mx-auto h-[160px] w-[160px]"><circle cx="80" cy="80" r={radius} fill="none" stroke="rgba(255,255,255,.08)" strokeWidth="18" />{segments.map((segment) => { const dash = segment.value / total * circumference; const node = <circle key={segment.label} cx="80" cy="80" r={radius} fill="none" stroke={segment.color} strokeWidth="18" strokeDasharray={`${dash} ${circumference - dash}`} strokeDashoffset={-offset} transform="rotate(-90 80 80)" />; offset += dash; return node; })}<circle cx="80" cy="80" r="34" fill="#070b17" /><text x="80" y="76" textAnchor="middle" fontSize="18" fill="#fff">{total}</text><text x="80" y="95" textAnchor="middle" fontSize="10" fill="rgba(255,255,255,.58)">records</text></svg><div className="space-y-3">{segments.map((segment) => <div key={segment.label} className="flex items-center justify-between rounded-2xl bg-black/20 px-4 py-3"><span className="flex items-center gap-3 text-sm text-white"><i className="h-3.5 w-3.5 rounded-full" style={{ backgroundColor: segment.color }} />{segment.label}</span><span className="text-sm text-white/85">{Math.round(segment.value / total * 100)}%</span></div>)}</div></div>;
}
