import { useMemo } from 'react';
import type { ReactNode } from 'react';
import type { Earthquake } from '@/types';
import { timeMs } from '@/features/dashboard/utils/data';
import { DepthDonut, Empty, MagnitudeColumns, ScatterChart, StrongestList, TrendChart } from './GlobalAnalyticsVisuals';

const accents = ['#ef4444', '#f97316', '#fbbf24', '#fb923c', '#f59e0b'];

export default function GlobalMapAnalytics({ events }: { events: Earthquake[] }) {
  const strongest = useMemo(() => [...events].sort((a, b) => b.magnitude - a.magnitude).slice(0, 4), [events]);
  const distributions = useMemo(() => {
    const magnitudeCounts = [0, 0, 0, 0, 0]; const depthCounts = [0, 0, 0];
    let maxMagnitude = 1; let maxDepth = 1; let m5Plus = 0; let tsunami = 0;
    events.forEach((event) => {
      maxMagnitude = Math.max(maxMagnitude, event.magnitude); maxDepth = Math.max(maxDepth, event.depth);
      if (event.magnitude >= 7) magnitudeCounts[0] += 1; else if (event.magnitude >= 6) magnitudeCounts[1] += 1; else if (event.magnitude >= 5) magnitudeCounts[2] += 1; else if (event.magnitude >= 4) magnitudeCounts[3] += 1; else magnitudeCounts[4] += 1;
      if (event.depth < 30) depthCounts[0] += 1; else if (event.depth < 150) depthCounts[1] += 1; else depthCounts[2] += 1;
      if (event.magnitude >= 5) m5Plus += 1; if (event.tsunami) tsunami += 1;
    });
    return { magnitude: [['M7+', magnitudeCounts[0]], ['M6-6.9', magnitudeCounts[1]], ['M5-5.9', magnitudeCounts[2]], ['M4-4.9', magnitudeCounts[3]], ['M<4', magnitudeCounts[4]]] as [string, number][], depth: [['0-30 km', depthCounts[0]], ['30-150 km', depthCounts[1]], ['150+ km', depthCounts[2]]] as [string, number][], maxMagnitude, maxDepth, m5Plus, tsunami };
  }, [events]);
  const { magnitude, depth, maxMagnitude, maxDepth } = distributions;
  const trend = useMemo(() => buildTrend(events), [events]);
  return <div className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-2 px-1"><div><p className="font-serif text-[10px] font-black uppercase tracking-[0.2em] text-orange-200">Live earthquake analytics</p><p className="mt-1 font-serif text-xs font-medium text-slate-500">Aligned summaries of the activity shown on the Earth</p></div><span className="rounded-full border border-orange-300/15 bg-orange-300/10 px-2.5 py-1 font-serif text-[10px] font-black text-orange-200">{events.length} events</span></div><div className="grid min-w-0 grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3"><AnalyticsPanel title="Earthquake count over time" subtitle="Activity in the selected data" tone="cyan"><TrendChart data={trend} /></AnalyticsPanel><AnalyticsPanel title="Magnitude distribution" subtitle="Events by magnitude band" tone="orange"><MagnitudeColumns data={magnitude} colors={accents} /></AnalyticsPanel><AnalyticsPanel title="Depth distribution" subtitle="How deep events occurred" tone="violet"><DepthDonut data={depth} colors={['#ef4444', '#f97316', '#fbbf24']} /></AnalyticsPanel><AnalyticsPanel title="Depth vs magnitude" subtitle="Each point is an earthquake" tone="rose"><ScatterChart events={events} maxMagnitude={maxMagnitude} maxDepth={maxDepth} /></AnalyticsPanel><AnalyticsPanel title="Strongest earthquakes" subtitle="Largest events in this view" tone="red"><StrongestList events={strongest} /></AnalyticsPanel><AnalyticsPanel title="Earthquake summary" subtitle="A quick view of the current data" tone="amber"><div className="grid grid-cols-3 gap-2"><Stat label="Total" value={events.length} /><Stat label="M5+" value={events.filter((event) => event.magnitude >= 5).length} /><Stat label="Tsunami" value={events.filter((event) => event.tsunami).length} /></div></AnalyticsPanel></div></div>;
}

function buildTrend(events: Earthquake[]) { if (!events.length) return []; const timestamps = events.map((event) => timeMs(event.time)).filter(Boolean); const end = Math.max(...timestamps, Date.now()); const start = Math.min(...timestamps, end - 6 * 24 * 60 * 60 * 1000); const span = Math.max(60 * 60 * 1000, end - start); const buckets = Array.from({ length: 7 }, (_, index) => ({ label: `${index + 1}`, count: 0 })); events.forEach((event) => { const index = Math.min(6, Math.max(0, Math.floor(((timeMs(event.time) - start) / span) * 7))); buckets[index].count += 1; }); return buckets; }
function AnalyticsPanel({ title, subtitle, children, tone }: { title: string; subtitle: string; children: ReactNode; tone: 'cyan' | 'orange' | 'violet' | 'rose' | 'red' | 'amber' }) { const toneStyles = { cyan: 'border-cyan-300/20 text-cyan-100', orange: 'border-orange-300/20 text-orange-100', violet: 'border-violet-300/20 text-violet-100', rose: 'border-rose-300/20 text-rose-100', red: 'border-red-300/20 text-red-100', amber: 'border-amber-300/20 text-amber-100' }[tone]; return <section className={`flex min-h-[210px] min-w-0 flex-col rounded-2xl border bg-gradient-to-br from-white/[0.10] via-white/[0.045] to-slate-950/35 p-3 shadow-[0_16px_38px_rgba(0,0,0,.24)] backdrop-blur-xl ${toneStyles}`}><div className="mb-3 flex min-h-[42px] items-start justify-between gap-2"><div className="min-w-0"><p className="break-words font-serif text-[11px] font-black uppercase leading-tight tracking-[0.12em]">{title}</p><p className="mt-1 break-words font-serif text-[10px] font-medium leading-tight text-slate-400">{subtitle}</p></div><span className="mt-0.5 h-2 w-2 shrink-0 rounded-full bg-current shadow-[0_0_10px_currentColor]" /></div><div className="min-h-0 flex-1">{children}</div></section>; }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-white/10 bg-white/[0.05] p-2"><p className="font-serif text-[9px] font-black uppercase tracking-[0.14em] text-slate-400">{label}</p><p className="mt-1 font-serif text-xl font-black text-white">{value}</p></div>; }
